### ISSUE TITLE
Issues to fix before adding to the plugin marketplace

### ISSUE THREAD

**Issue by bjsi** [micharied/flashcard-from-headline-to-body#1]
- [x] README needs to be finished. Maybe show a pic of what it looks like?
- [x] Here you can do this instead
https://github.com/micharied/flashcard-from-headline-to-body/blob/05d8cba5b7cb8a82e7d0545240853d1107b53ba3/src/widgets/flashcard_from_headline_to_body.tsx#L12-L14

```ts
const rem = useTracker(async (rp) => {
  const ctx = await rp.widget.getWidgetContext<WidgetLocation.DocumentBelowTitle();
  return await rp.rem.findOne(ctx?.documentId)
}. [])
```

This makes sure it works, even if the document isn't focused.

**Comment by micharied** [comment]
Thank you for the feedback! I just pushed an update. :)
